build-notebook:
        bash scripts/build-noteboook-dockerfile.sh

build-app:
		bash scripts/build-scripts/build-app-dockerfile.sh

build-development:
        bash scripts/build-scripts/build-all.sh


build-run-notebook:
        bash scripts/run-scripts/run-notebook.sh

build-run-app:
		bash scripts/run-scripts/run-application.sh

build-run-development:
        bash scripts/run-scripts/run-development.sh


build-run-tests:
        bash scripts/test-scripts/run-tests.sh





