FROM python:3.6.4
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY src/requirements-application.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements-application.txt

# Copy static attrs (non dev) to /usr/src/app
COPY src .
COPY bin .
COPY tests .
COPY scripts .