# DO NOT TOUCH
# (Unless you want to debug a bit)
FROM {{cookiecutter.project_slug}}-application

# CHANGE ANYTHING FROM HERE DOWN
COPY notebooks/requirements-notebook.txt .
RUN pip install -r requirements-notebook.txt
RUN jupyter contrib nbextension install --user
RUN jupyter nbextensions_configurator enable --user
COPY notebooks/ notebooks
