FROM python:3.6.4
RUN mkdir -p /usr/src/app
ENV PYTHONPATH=$PYTHONPATH:/usr/src/app
ENV PYTHONUNBUFFERED=1
WORKDIR /usr/src/app
COPY src/requirements-application.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements-application.txt

# Copy static attrs (non dev) to /usr/src/app
COPY src/ src/
COPY bin/ bin/
COPY tests/ tests/
COPY scripts/ scripts/
